FROM ubuntu:22.04

RUN apt update
RUN apt install -y --no-install-recommends \
    ca-certificates \
    nano \
    git \
    openssh-client \
    make \
    gcc \
    python3 \
    python3-pip \
    curl \
    wget \
    xz-utils \
    pkg-config \
    libgmp-dev \
    zlib1g-dev
